### ISSUE TITLE
Find a better way to get the CC jar

### ISSUE THREAD

**Issue by apemanzilla** [Lignum/CCEmuX#12]
Kind of annoying how the CC jar URL pattern changes with each version, would be nice to find a universal alternative

**Comment by Lemmmy** [comment]
regex

**Comment by SquidDev** [comment]
You could trawl [this page](https://minecraft.curseforge.com/projects/computercraft/files) and look for a download link of a specific file. The download link should redirect to the Jar. I have some [sample trawling code](https://github.com/SquidDev-CC/accursed/blob/master/Services/ModFetcher.cs#L135) for a website I wrote a while back.

**Comment by Lemmmy** [comment]
the page's contents could change, though. i was thinking of making a centralized service ccdownload.info which serves the link to the latest cc jar (not redistribution) and also supports version e.g. ccdownload.info/1.60

**Comment by Lemmmy** [comment]
on second thought - curseforge has [an api](https://github.com/curseforge/api) - you could use that instead of trawling the page.

**Comment by apemanzilla** [comment]
I've been looking at the curseforge API but there isn't one that lists files for projects - at least, not one that I can find.

**Comment by Lemmmy** [comment]
curseforge also has an api, however it doesn't document anytgin

**Comment by Lemmmy** [comment]
my rbowser just died

**Comment by Lemmmy** [comment]
insteasd of a centralized service, howabout a github repo with a `latest` file and a file for each version?

**Comment by apemanzilla** [comment]
There seems to be an API endpoint for files `https://minecraft.curseforge.com/api/projects/67504/files?token=<your token>` but it always gives me this error `{"errorCode":1100,"errorMessage":"You do not have permission to access this method."}`

**Comment by apemanzilla** [comment]
Hopefully when (or if...) CC eventually goes open source there will be a maven repository containing it. For now I'm closing this.
