### ISSUE TITLE
TRoR support

### ISSUE THREAD

**Issue by apemanzilla** [Lignum/CCEmuX#18]
An improved headless mode for embedded uses (i.e. CI) would be useful, with a way to allow CC to communicate with external programs. Current ideas include ANSI escape sequences and sockets.

@SquidDev, thoughts?

Progress:
- [ ] Output
- [ ] Keyboard Input
- [ ] Mouse Input
- [ ] Extensions

**Comment by SquidDev** [comment]
I haven't really thought about how to implement the Howl CI yet so I can't say exactly what I need. ANSI escape sequences would be more useful developing over SSH or something - but then you'd need to handle key (and maybe mouse) events - I guess you could use NCurses bindings?

> Something which would be really useful would be to output the terminal calls and a timestamp: this way you can reproduce terminal output and render it as a gift, HTML canvas, etc...

This probably translates into sockets or printing to standard output: both are relatively easy to capture though I guess the latter isn't useful if you already print (and I think ComputerCraft and CCTweaks do already). Again it would be useful if this back end supported queuing events: whilst the CI wouldn't need it you could develop other programs which do (such as a remote emulator).

I don't know if we'd need to design a binary protocol or just use [TRoR](http://www.computercraft.info/forums2/index.php?/topic/6484-rfc-tror-terminal-redirection-over-rednet/) (though we'd need to add support for `term.blit`).

**Comment by apemanzilla** [comment]
I'll look into ANSI rendering a bit more. It's definitely possible but don't get your hopes up about usability.

For socket/IO streaming I think a simple text-based protocol would be sufficient - something like `ID action args`, eg `0 setCursorPos 5 7`

**Comment by SquidDev** [comment]
If we're doing text based then I'd just go for TRoR: it is pretty trivial to parse/generate and is an existing "standard". I understand about ANSI: I've had a go in the past and it was always a pain to get working.

**Comment by apemanzilla** [comment]
Fair enough. For simplicity's sake I'll implement TRoR first.

**Comment by apemanzilla** [comment]
Fair enough. I'll work on TRoR first, adding a `TT` code for `blit` (Since `TB`, `TL`, and `TI` are all taken)

**Comment by apemanzilla** [comment]
As far as input goes in TRoR, would you prefer a generic `EQ` packet that just queues events from the arguments, or individual types like `EM` for mouse click, `EC` for char, `EK` for key, etc.

**Comment by SquidDev** [comment]
[Lyqyd suggests](http://www.computercraft.info/forums2/index.php?/topic/6484-rfc-tror-terminal-redirection-over-rednet/page__view__findpost__p__54608) a generic `EV` packet: I'd say this makes more sense then splitting it into separate packets.

**Comment by apemanzilla** [comment]
True. That brings up another potential issue - converting the strings to Lua types. It's easy enough to parse them into primitives but what happens if there's a `char` event for `1`, which would be parsed as a number despite the fact that it should be a string/char.

A similar issue occurs with `blit` - the first argument contains arbitrary text, which would mess up the parsing if the text contains a comma (used to delimit arguments).

**Comment by SquidDev** [comment]
Lyqyd suggests using `textutils.serialize`: whilst *technically* events can contain tables I think we can probably ignore that - we'd just have to quote the strings.

The alternative would be to add type fields at the beginning of each entry, with a length for strings.

**Comment by apemanzilla** [comment]
That could work for events. For `blit` I think the easiest solution would be to just parse the arguments backwards - since the last two can never contain commas and must have a length equal to the first.

**Comment by Lemmmy** [comment]
![](http://totally.shitty.download/concrete.png)

**Comment by Lignumm** [comment]
We could make a Gitter for this if you guys wanna have an intense debate.

**Comment by Lemmmy** [comment]
Gitters are poopy.

**Comment by apemanzilla** [comment]
Once we decide on the final TRoR spec I'll implement this at the emulation level so that it's independent of the renderer.

**Comment by apemanzilla** [comment]
Wrong button 😛

**Comment by apemanzilla** [comment]
I've implemented basic functionality for this as of 9676518.

@SquidDev if you could try this out and make sure I didn't mess up I'd appreciate it. Run it with `-r AWT,TRoR_STDIO`. It will output packets into stdout, prefixed by `[TRoR]` (eg `[TRoR]TE:1;` where the metadata represents the computer ID). Right now it does not accept input, but it should output everything just fine (including `SP` when created and `SC` when stopped). Let me know if there's anything I need to change.

**Comment by Lemmmy** [comment]
what is trror

**Comment by apemanzilla** [comment]
https://github.com/oeed/CraftOS-Standards/blob/master/Protocols/tror.md

**Comment by apemanzilla** [comment]
More work on this, basic keyboard input is now supported as of  caa3be9. You can now queue `char`, `key`, `key_up`, and `paste` events using TRoR commands such as `EV:0;"key",28`, where the metadata represents the target computer ID.

Right now, all other events will be ignored.
