### ISSUE TITLE
Resource Pack Support

### ISSUE THREAD

**Issue by apemanzilla** [Lignum/CCEmuX#24]
Support for custom resource packs so that custom fonts and custom ROMs can be used, pretty self explanatory.

**Comment by Lignumm** [comment]
Let's slow down a bit and get custom fonts to work first. If you go in the font rendering code, you'll see a bunch of hardcoded values, which I'm not sure how to retrieve from custom fonts.

**Comment by Lemmmy** [comment]
json files for font definitions

**Comment by apemanzilla** [comment]
Implemented in #58

**Comment by apemanzilla** [comment]
Implemented in eb52cc62286abc440bfbc16c78ac30c3d278925e
