### ISSUE TITLE
Can there be CC Mod addons to use with CCTweaks?

### ISSUE THREAD

**Issue by daelvn** [Lignum/CCEmuX#45]
Just that, I'd really like to use [this](http://www.computercraft.info/forums2/index.php?/topic/28103-mc-189cctweaks-ccgit/)

**Comment by demhydraz** [comment]
What a shitty issue

**Comment by Lignumm** [comment]
no

**Comment by demhydraz** [comment]
close this!!

**Comment by Lignumm** [comment]
ok

**Comment by apemanzilla** [comment]
At that point we'd be rewriting Forge and Minecraft pretty much

**Comment by demhydraz** [comment]
I mean, you could implement a mod loader and modding API for CCEmuX (heck - I could do it), but arbitrary compatibility with Forge mods? Nah.

**Comment by apemanzilla** [comment]
I've been talking with @Lemmmy about a plugin system for CCEmuX anyways, so that's probably the route we would take.

**Comment by demhydraz** [comment]
that's a good path to world domination

**Comment by demhydraz** [comment]
☑️

**Comment by KingofGamesYami** [comment]
It probably wouldn't be extremely difficult to simply port CCGit over to CCEmuX.  It's basically just registering stuff using CCTweaks, which you have integrated (I think?).  I don't interact directly with FML except for registering and a few log messages.

**Comment by Lemmmy** [comment]
Wait until we make the plugin system, then we can port as many plugins/mods as we like.

The plugin system will be similar to forge mods, but less shitty. It will ship with default plugins (the AWT renderer, TRoR renderer and a few more) and others can be dropped in (probably as jar files). CCGit would make a perfect plugin. So if you could hold out until we've implemented those, that would be great.

**Comment by KingofGamesYami** [comment]
I'll put this on hold then, probably try to add more functionality to CCGit in the meantime.

**Comment by Lemmmy** [comment]
I've created #46 - when the plugin system is done we'll get in touch with you and see if we can arrange a CCGit plugin.

**Comment by apemanzilla** [comment]
@KingofGamesYami if you're still interested the plugin system is (for the most part) done now.
