### ISSUE TITLE
Plugin system + base plugins

### ISSUE THREAD

**Issue by Lemmmy** [Lignum/CCEmuX#46]
- [x] Plugin system
- - Load jars and plugin classes with a [ServiceLoader](http://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html), and plugin classes extend a base `Plugin` class.
```
// CCEmuXPlugin.java
public interface CCEmuXPlugin {
    register(some context variable);
}

// CCEmuXLoader.java
for(CCEmuXPlugin plugin : ServiceLoader.load(CCEmuXPlugin.class, classLoader)) {
    plugin.register(context);
}
```
- [x] Port the renderers to plugins
- [x] Example plugins + API documentation

# Base Plugins
- [ ] Rednet / Modem
- [ ] Simulated turtle world
- [ ] Noteblock
- [ ] Shared folders (configurable mountable disk drives)
- - See: IMedia, ComputerCraftAPI.createSaveDirMount, ComputerCraftAPI.createResourceMount
- [ ] CCGit

**Comment by apemanzilla** [comment]
There are two main issues I'm seeing with the plugin system. The first is development - we need an easy way to debug plugins live. This could probably be solved with submodules and Gradle multiproject support, but it would complicate things a bit.

The second is how the plugins will be loaded - mainly, included plugins. We would probably be using a custom classloader to handle plugin detection. This would work for loading external plugins for jars, but how would we find plugins included in the main jar?

**Comment by Lemmmy** [comment]
Reflection

**Comment by apemanzilla** [comment]
Yes, but the problem of actually finding the plugin classes remains.

**Comment by Lemmmy** [comment]
Are we using Guava?

**Comment by apemanzilla** [comment]
Yes.

**Comment by Lemmmy** [comment]
[Google Reflections](https://github.com/ronmamo/reflections)

**Comment by apemanzilla** [comment]
For that to work we would need all plugins to be in a specific package, which isn't practical.

**Comment by Lignumm** [comment]
yeah but what about v1

**Comment by Lemmmy** [comment]
We could have the plugin provide a `plugin.ini` file which defines the main class?

**Comment by SquidDev** [comment]
Could you not use the built-in META-INF service thing instead? So have a "service" class and use the [ServiceLoader](http://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html). This way we're not re-inventing the wheel.

**Comment by Lemmmy** [comment]
If we do this, we could even include base plugins in the main project and not as submodules, where the `plugin.ini` just points to e.g. `net.clgd.ccemux.plugins.base.gdx`

**Comment by Lignumm** [comment]
![](https://shitty.download/hzYeTP.png)
Look how close we are

**Comment by apemanzilla** [comment]
Huh, for some reason I thought `ServiceLoader` was a Java EE thing.

**Comment by Lemmmy** [comment]
The plugin system will help with v1 a lot - it will make it easier to add things like peripherals, more renderers, and generally better integration

**Comment by SquidDev** [comment]
I'm happy to chip in wherever it may be useful, though obviously Plethora takes priority 😄.

**Comment by Lemmmy** [comment]
I agree with the ServiceLoader approach. Shall it just link to the package, or the main class? Will it use annotations, or extend a Plugin class?

**Comment by justync7** [comment]
why not just annotate the main plugin classes like forge does with mods e.g
`@Plugin(name = "MyPlugin", version = "1.0")`

**Comment by apemanzilla** [comment]
Just implement `Plugin` and keep it simple IMO.

**Comment by Lignumm** [comment]
yeah but then we'll have reflection and the project will be disgusting and sticky

**Comment by Lemmmy** [comment]
That's what we were discussing justyn, however the problem is loading the annotations. You have to search the entire classpath for packages, and then classes in those packages, and then annotations in those classes.

**Comment by Lemmmy** [comment]
@Lignumm there's no way to load plugins without reflection

**Comment by apemanzilla** [comment]
@Lignumm the project is already disgusting and stinky, look at how it handles CC....

**Comment by Lignumm** [comment]
@Lemmmy sure but the less weird reflection we can get, the better

but what would also help v1 is if we delayed a plugin system until after v1

**Comment by Lemmmy** [comment]
Midiots would like it more if it had a huge **PLUGINS!!!!!** banner, and people releasing plugins for it days after release.

**Comment by apemanzilla** [comment]
Yami has already offered to implement functionality for CCGit when it's ready.

**Comment by Lignumm** [comment]
ok if you insist

**Comment by SquidDev** [comment]
With service loaders you'd just have something like:

```java
// CCEmuXPlugin.java
public interface CCEmuXPlugin {
    register(some context variable);
}

// CCEmuXLoader.java
for(CCEmuXPlugin plugin : ServiceLoader.load(CCEmuXPlugin.class, classLoader)) {
    plugin.register(context);
}
```

**Comment by apemanzilla** [comment]
@SquidDev and would that find all services (plugins) present in the given classloader?

**Comment by Lignumm** [comment]
@SquidDev no idea what those are, but they look good to me.

**Comment by Lemmmy** [comment]
@Lignumm [here](https://docs.oracle.com/javase/tutorial/ext/basics/spi.html)

**Comment by SquidDev** [comment]
@apemanzilla You have to specify them in a `META-INF/services/java.net.clgd.ccemux.CCEmuXPlugin` file, but really that isn't much of a faff. 

The issue with any other way is you have to load every class up (or read the class file), check it implements an interface/annotation and then instantiate it. Whilst it is more "friendly" it increases startup time and is a hassle.

**Comment by Lemmmy** [comment]
That's how Forge does it afaik

**Comment by apemanzilla** [comment]
Yeah, I get that. Alright, can we all agree on using `ServiceLoader`?

**Comment by demhydraz** [comment]
I think annotations + reflection is better for the plugin developer than a `ServiceLoader`

**Comment by apemanzilla** [comment]
@demhydraz how so?

**Comment by Lemmmy** [comment]
Reflection is slow though

**Comment by demhydraz** [comment]
Not having to deal with `META-INF`, for starters.

**Comment by apemanzilla** [comment]
Well I mean `META-INF` is already being used for the splash screen and the main class and whatnot...

**Comment by Lignumm** [comment]
Yeah but we also don't want to reinvent the :ferris_wheel:. Dealing with META-INF is easy if you use gradle and aren't an idiot.

**Comment by Lemmmy** [comment]
Gradle can automate META-INF with a resource file

**Comment by SquidDev** [comment]
Reflection wouldn't be slow beyond the initial startup. I think the trade off here is "development cost": having to maintain a `META-INF` services file vs startup cost: having to search for plugins at runtime.

**Comment by Lemmmy** [comment]
Well slow initial startup is also a problem - people want to open the emu and get working ASAP

**Comment by demhydraz** [comment]
Are plugins even going to be loaded synchronously?

**Comment by Lemmmy** [comment]
Well java async is kinda crappy

**Comment by demhydraz** [comment]
I think that's implied

**Comment by apemanzilla** [comment]
One other issue is that if we're using `META-INF` it will only work when run from a jar. If run directly from the class files, as many IDEs do, it won't work properly.

**Comment by Lemmmy** [comment]
Then what about the `plugin.info` approach?

**Comment by demhydraz** [comment]
Sorry - which approach, now?

**Comment by SquidDev** [comment]
I _think_ `META-INF` is still loaded when in a directory rather than a jar as it counts as a resource. I might be wrong though: I have no source.

**Comment by apemanzilla** [comment]
@SquidDev it is not - try `gradle run` in CCEmuX and you'll notice it doesn't show the splash screen like it does if you do `gradle runShadow`

**Comment by Lemmmy** [comment]
A `plugin.ini` resource file in the jar which contains a link to the main class, e.g.

```
[Plugin]
MainClass = my.cool.CCEmuXPlugin
Name = My Cool CCEmuX Plugin
```

**Comment by demhydraz** [comment]
Ehh - while that's definitely more convenient than META-INF and probably faster than searching a bunch of jars in a directory, I'm not convinced. If we're doing that, then why not do META-INF?

**Comment by Lemmmy** [comment]
Because some IDEs and Gradle do not load META-INF.

**Comment by apemanzilla** [comment]
@demhydraz we would still have to search all the jars in the directory regardless of which approach we take. It's not very slow to list files anyways...

**Comment by Lignumm** [comment]
http://stackoverflow.com/questions/13254620/meta-inf-services-in-jar-with-gradle#13257915

**Comment by justync7** [comment]
Just use Annotations and Reflection, It may be a slow startup but nothing is slower than Minecraft itself.

**Comment by apemanzilla** [comment]
@justync7 I don't know if it's even possible to find a list of all classes on the classpath though, which we would need to be able to do to find plugin classes.

**Comment by Lemmmy** [comment]
@justync7 the problem is loading the plugins with reflection. You cannot do a recursive * annotation search with any of the reflection libraries.

**Comment by justync7** [comment]
Well then how does Forge do it?

**Comment by apemanzilla** [comment]
They iterate the files within the jars IIRC. Which would work, but still would cause issues when not packaged as a jar.

**Comment by justync7** [comment]
No... It would work just fine the way they do it when not packaged as a jar, else my development environment is living a lie.

**Comment by apemanzilla** [comment]
@justync7 If you're using ForgeGradle I'm pretty sure they package it as a jar every time you run it...

**Comment by justync7** [comment]
Nope. It uses a launch configuration on Minecraft and doesn't build the jar once. It loads the direct class files.

**Comment by apemanzilla** [comment]
@justync7 it looks like they have multiple methods of mod discovery, including both jar and directory-based searching (as seen in the source code [here](https://github.com/MinecraftForge/MinecraftForge/tree/1.11.x/src/main/java/net/minecraftforge/fml/common/discovery))

**Comment by SquidDev** [comment]
Yeah. FML has separate "discoverers" for jars and directories. Basically we'd want to implement something like [this](https://github.com/MinecraftForge/MinecraftForge/tree/1.11.x/src/main/java/net/minecraftforge/fml/common/discovery).

**Comment by Lemmmy** [comment]
ASM?!?!?!

**Comment by SquidDev** [comment]
Well you have to, otherwise you end up loading every class and using reflection which probably takes even longer.

**Comment by Lemmmy** [comment]
Remember that I'm the one implementing this

**Comment by SquidDev** [comment]
> It is not - try gradle run in CCEmuX and you'll notice it doesn't show the splash screen like it does if you do gradle runShadow

@apemanzilla The issue here, as @Lignumm has pointed out, is that you are creating the META-INF files at when the jar is packaged. If you had an explicit `MANIFEST` file then it would work fine. I don't think we'd have this problem with the services files as you have to write it yourself.

**Comment by demhydraz** [comment]
> Remember that I'm the one implementing this

_I_ could probably implement this too, so shush

**Comment by apemanzilla** [comment]
Who knew the biggest problem with this feature would be finding the dang plugins?

**Comment by Lemmmy** [comment]
I still don't see anything wrong with the `plugin.ini` idea

**Comment by justync7** [comment]
Sounds easier than messing with MANIFEST.

**Comment by demhydraz** [comment]
Apart from the "oh no, this plugin I have installed is not being loaded! better open an issue"?

**Comment by SquidDev** [comment]
> I still don't see anything wrong with the `plugin.ini` idea

I don't either. I'm just pushing for `ServiceLoader` as it is basically the same but built in to Java.

**Comment by Lemmmy** [comment]
The user's aren't making the `plugin.ini` - the mod developers are

**Comment by apemanzilla** [comment]
Alright then, can we get a vote?

:laughing: for services via `META-INF`
:confused: for `plugin.ini`
:heart: for iteration and reflection

**Comment by apemanzilla** [comment]
Everyone comfortable with services?

**Comment by demhydraz** [comment]
¯\_(ツ)_/¯

**Comment by apemanzilla** [comment]
You dropped this \\

**Comment by justync7** [comment]
No one voted for services ;p
!()[http://nigga.pw/stands_price.png}

**Comment by Lemmmy** [comment]
Github marks the reaction as "laugh" but the :laugh emoji is an XD

**Comment by apemanzilla** [comment]
Blame GitHub for their inconsistent emoji names.

**Comment by demhydraz** [comment]
> You dropped this \

Wrong, I dropped \\\\

**Comment by apemanzilla** [comment]
You dropped \\\\\\\\?

**Comment by demhydraz** [comment]
No, I dropped `\\`

**Comment by justync7** [comment]
No. He dropped \\\\\\\\.

**Comment by demhydraz** [comment]
I know what I dropped, ok?

**Comment by apemanzilla** [comment]
Anyways, now that we have discovery sorted out, how do we want plugins to be structured? Annotations (:heart:) or just subclasses (:confused:)

**Comment by justync7** [comment]
Extension *AND* Annotation.

**Comment by SquidDev** [comment]
I'm not sure I understand the question. Annotations on methods or classes?

**Comment by demhydraz** [comment]
Classes, I'd presume

**Comment by apemanzilla** [comment]
@SquidDev Why not both?

**Comment by demhydraz** [comment]
Yeah, that

**Comment by Lemmmy** [comment]
Annotations require more reflection

**Comment by apemanzilla** [comment]
Reflection is pretty much a given regardless of what we do at this point.

**Comment by Lemmmy** [comment]
Yes but annotation reflection requires libraries or 150 lines of code - class reflection requires 3 lines of code

**Comment by SquidDev** [comment]
Can you provide an example of the API using annotations? I'm probably being really dumb here. The whole point of services is that you don't need to touch reflection, just implement an interface.

**Comment by apemanzilla** [comment]
What do you mean @Lemmmy? `Class<?>.getDeclaredAnnotation` doesn't work?

**Comment by Lemmmy** [comment]
```
@CCEmuXPlugin(version="1.0")
public class GoodPlugin {
    @PluginEvent
    public void onPluginInit(PluginInitialisedEvent e) {
    
    }
}
```
something like this?

**Comment by Lemmmy** [comment]
the latter is easier to write hooks for, too.

**Comment by apemanzilla** [comment]
I've opened a PR for this issue in #58
